### ISSUE TITLE
Refactor assigned packages

### ISSUE THREAD

**Issue by tylernhoward** [Tayham/FreeCol#4]
Decide whether class needs to be refactored/have tests and fill out corresponding google doc

**Comment by patelaman** [comment]
Commit eb95d53 addresses this issue. Refactored code using SonarLint and Unnecessary Code Detector.

**Comment by Tayham** [comment]
Commit [56c0397](https://github.com/Tayham/FreeCol/commit/78adde6fe1a8f809123e9022bb64cad8656c0397) addresses this issue.

**Comment by mjkrause14** [comment]
Commit 5fb358f addresses this issue
